[project]
name = "contmapf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Square596", email = "artem211201@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
contmapf = "contmapf:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
